export const ON_REGISTRATION_INIT = 'ON_REGISTRATION_INIT';
export const ON_REGISTRATION_SUCCESS = 'ON_REGISTRATION_SUCCESS';
export const ON_REGISTRATION_FAILED = 'ON_REGISTRATION_FAILED';

export const ON_LOG_IN_INIT = 'ON_LOG_IN_INIT';
export const ON_LOG_IN_SUCCESS = 'ON_LOG_IN_SUCCESS';
export const ON_LOG_IN_FAILED = 'ON_LOG_IN_FAILED';

export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';

export const GET_DATA_CURRENT_PROFILE = 'GET_DATA_CURRENT_PROFILE';

export const GET_DATA_CURRENT_PROFILE_INIT = 'GET_DATA_CURRENT_PROFILE_INIT';
export const GET_DATA_CURRENT_PROFILE_SUCCESS = 'GET_DATA_CURRENT_PROFILE_SUCCESS';
export const GET_DATA_CURRENT_PROFILE_FAILED = 'GET_DATA_CURRENT_PROFILE_FAILED';

export const UPDATE_DATA_CURRENT_PROFILE_INIT = 'UPDATE_DATA_CURRENT_PROFILE_INIT';
export const UPDATE_DATA_CURRENT_PROFILE_SUCCESS = 'UPDATE_DATA_CURRENT_PROFILE_SUCCESS';
export const UPDATE_DATA_CURRENT_PROFILE_FAILED = 'UPDATE_DATA_CURRENT_PROFILE_FAILED';

export const GET_LAST_MESSAGES_INIT = 'GET_LAST_MESSAGES_INIT';
export const GET_LAST_MESSAGES_SUCCESS = 'GET_LAST_MESSAGES_SUCCESS';
export const GET_LAST_MESSAGES_FAILED = 'GET_LAST_MESSAGES_FAILED';

export const ADD_NEW_MESSAGE = 'ADD_NEW_MESSAGE';