export const ON_REGISTRATION_INIT = 'ON_REGISTRATION_INIT';
export const ON_REGISTRATION_SUCCESS = 'ON_REGISTRATION_SUCCESS';
export const ON_REGISTRATION_FAILED = 'ON_REGISTRATION_FAILED';

export const ON_LOG_IN_INIT = 'ON_LOG_IN_INIT';
export const ON_LOG_IN_SUCCESS = 'ON_LOG_IN_SUCCESS';
export const ON_LOG_IN_FAILED = 'ON_LOG_IN_FAILED';

export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';